version: '3.9'
services:
  localstack:
    container_name: localstack
    image: localstack/localstack:0.14.4
    ports:
      - "4566-4599:4566-4599"
    environment:
      - EXTRA_CORS_ALLOWED_ORIGINS=https://app.localstack.cloud
      - DISABLE_CORS_CHECKS=1
      - SERVICES=sns
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - AWS_DEFAULT_REGION=us-east-1
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
    volumes:
      - "./init-scripts:/docker-entrypoint-initaws.d"
      - "./config:/configs"
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"